### ISSUE TITLE
Create fobject.py similar to waobject.py from tithiwa, logic is almost done.

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithif#1]
check [waobject.py](https://github.com/Tithibots/tithiwa/blob/main/tithiwa/waobject.py)
Just remove all functions that are specific to tithiwa for example this [_open_whatsapp_if_not_opened(self):](https://github.com/Tithibots/tithiwa/blob/7cef0e13b6ab6f8050060bb3cbaad0f59f79c19e/tithiwa/waobject.py#L37-L39)

**Comment by pyvelkov** [comment]
do you want the functions that are specific to whatsapp to be removed or changed to facebook?
i.e.
`#from
def _open_whatsapp_if_not_opened(self):
        if self.browser.current_url.find("web.whatsapp") == -1:
            self.browser.get("https://web.whatsapp.com/")`

`#to
def _open_facebook_if_not_opened(self):
        if self.browser.current_url.find("web.facebook") == -1:
            self.browser.get("https://www.facebook.com/")`

**Comment by NavpreetDevpuri** [comment]
@pyvelkov 
yes you can change `_open_whatsapp_if_not_opened(self)`
But other functions are too specific for message purposes so we will gonna create another class to handle Facebook messages.
i.e more interesting challenges are coming soon 🧐

**Comment by pyvelkov** [comment]
ok, so you just want them gone? no implementation?

**Comment by NavpreetDevpuri** [comment]
yes

**Comment by pyvelkov** [comment]
ok, cool. I will get to work. Thanks for assigning :D
